import {
  buildDjiFieldMetadata,
  type DjiFieldMetadata,
  type DjiFieldRow,
} from './dji-field-metadata'

export const DJI_AIRCRAFT_PROPERTY_DOC_URL =
  'https://github.com/dji-sdk/Cloud-API-Doc/blob/master/docs/cn/60.api-reference/20.dock-to-cloud/00.mqtt/10.aircraft/10.m3d-properties.md'

export const DJI_AIRCRAFT_PROPERTY_DOC_DATE = '2026-08-26'

const DJI_AIRCRAFT_FIELD_ROWS = [
  ['best_link_gateway', '最佳图传网关 SN', 'text', '', '蛙跳任务中，飞行器同时对频多个机场时，当前图传连接质量最好的机场序列号。', 'r', '1'],
  ['wireless_link_topo', '图传连接拓扑', 'struct', '', '飞行器、机场或遥控器之间的图传对频与连接拓扑。', 'r', '1'],
  ['»secret_code', '加密编码', 'array', '{"size":28,"item_type":"int"}', '图传链路使用的加密编码数据。', '', '0'],
  ['»center_node', '飞行器对频信息', 'struct', '', '图传拓扑中的飞行器中心节点信息。', '', '0'],
  ['»»sdr_id', 'SDR 扰码', 'int', '', '设备在 SDR 图传链路中的扰码标识。', '', '0'],
  ['»»sn', '设备 SN', 'text', '', '当前拓扑节点的设备序列号。', '', '0'],
  ['»leaf_nodes', '已连接设备', 'array', '{"size":-,"item_type":"struct"}', '当前与飞行器连接的机场或遥控器节点。', '', '0'],
  ['»»sdr_id', 'SDR 扰码', 'int', '', '连接设备在 SDR 图传链路中的扰码标识。', '', '0'],
  ['»»sn', '设备 SN', 'text', '', '已连接机场或遥控器的设备序列号。', '', '0'],
  ['»»control_source_index', '控制源序号', 'int', '{"max":"2","min":"1","step":"1"}', '连接设备对应的控制源序号。', '', '0'],
  ['payload_index', '负载编号', 'text', '', '飞行器当前主相机负载索引，格式为 {type-subtype-gimbalindex}。', 'r', '0'],
  ['cameras', '飞行器相机信息', 'array', '{"size":-,"item_type":"struct"}', '飞行器各相机负载的拍摄、录像、变焦和测温状态。', 'r', '0'],
  ['»remain_photo_num', '剩余拍照张数', 'int', '', '当前存储空间预计还能拍摄的照片数量。', '', '0'],
  ['»remain_record_duration', '剩余录像时间', 'int', '{"unit_name":"秒 / s"}', '当前存储空间预计还能录像的时长。', '', '0'],
  ['»record_time', '视频录制时长', 'int', '{"unit_name":"秒 / s"}', '本次录像已经持续的时间。', '', '0'],
  ['»payload_index', '负载编号', 'text', '', '相机负载索引，格式为 {type-subtype-gimbalindex}。', '', '0'],
  ['»camera_mode', '相机模式', 'enum_int', '{"0":"拍照","1":"录像","2":"智能低光","3":"全景拍照"}', '相机当前所处的拍摄工作模式。', '', '0'],
  ['»photo_state', '拍照状态', 'enum_int', '{"0":"空闲","1":"拍照中"}', '相机当前是否正在执行拍照。', '', '0'],
  ['»screen_split_enable', '分屏状态', 'bool', '{"false":"关闭","true":"开启"}', '相机直播画面的分屏显示是否开启。', '', '0'],
  ['»recording_state', '录像状态', 'enum_int', '{"0":"空闲","1":"录像中"}', '相机当前是否正在录像。', '', '0'],
  ['»zoom_factor', '变焦倍数', 'float', '', '可见光变焦镜头当前的放大倍数。', '', '0'],
  ['»ir_zoom_factor', '红外变焦倍数', 'float', '', '红外镜头当前的放大倍数。', '', '0'],
  ['»liveview_world_region', '直播视场区域', 'struct', '', '变焦视场角在直播画面中的归一化区域，坐标原点位于左上角。', '', '0'],
  ['»»left', '区域左边界', 'float', '', '视场区域左上角的横向起点。', '', '0'],
  ['»»top', '区域上边界', 'float', '', '视场区域左上角的纵向起点。', '', '0'],
  ['»»right', '区域右边界', 'float', '', '视场区域右下角的横向终点。', '', '0'],
  ['»»bottom', '区域下边界', 'float', '', '视场区域右下角的纵向终点。', '', '0'],
  ['»photo_storage_settings', '照片存储设置', 'array', '{"size":-,"item_type":"enum_string"}', '拍照时需要保存的镜头类型集合。', '', '0'],
  ['»video_storage_settings', '视频存储设置', 'array', '{"size":-,"item_type":"enum_string"}', '录像时需要保存的镜头类型集合。', '', '0'],
  ['»wide_exposure_mode', '广角曝光模式', 'enum_int', '{"1":"自动","2":"快门优先","3":"光圈优先","4":"手动"}', '广角镜头当前使用的曝光模式。', '', '0'],
  ['»wide_iso', '广角感光度', 'int', '', '广角镜头当前配置的 ISO 感光度枚举值。', '', '0'],
  ['»wide_shutter_speed', '广角快门速度', 'int', '', '广角镜头当前配置的快门速度枚举值。', '', '0'],
  ['»wide_exposure_value', '广角曝光值', 'int', '', '广角镜头当前配置的曝光补偿枚举值。', '', '0'],
  ['»zoom_exposure_mode', '变焦曝光模式', 'enum_int', '{"1":"自动","2":"快门优先","3":"光圈优先","4":"手动"}', '变焦镜头当前使用的曝光模式。', '', '0'],
  ['»zoom_iso', '变焦感光度', 'int', '', '变焦镜头当前配置的 ISO 感光度枚举值。', '', '0'],
  ['»zoom_shutter_speed', '变焦快门速度', 'int', '', '变焦镜头当前配置的快门速度枚举值。', '', '0'],
  ['»zoom_exposure_value', '变焦曝光值', 'int', '', '变焦镜头当前配置的曝光补偿枚举值。', '', '0'],
  ['»zoom_focus_mode', '变焦对焦模式', 'enum_int', '{"0":"MF","1":"AFS","2":"AFC"}', '变焦镜头当前使用的手动或自动对焦模式。', '', '0'],
  ['»zoom_focus_value', '变焦对焦值', 'int', '', '变焦镜头当前的对焦位置值。', '', '0'],
  ['»zoom_max_focus_value', '最大对焦值', 'int', '', '变焦镜头支持的最大对焦位置值。', '', '0'],
  ['»zoom_min_focus_value', '最小对焦值', 'int', '', '变焦镜头支持的最小对焦位置值。', '', '0'],
  ['»zoom_focus_state', '变焦对焦状态', 'enum_int', '{"0":"空闲","1":"对焦中","2":"对焦成功","3":"对焦失败"}', '变焦镜头当前的自动对焦执行状态。', '', '0'],
  ['»ir_metering_mode', '红外测温模式', 'enum_int', '{"0":"关闭测温","1":"点测温","2":"区域测温"}', '红外相机当前采用的测温方式。', '', '0'],
  ['flysafe_database_version', '飞行安全数据库版本', 'text', '{"length":"64"}', '飞行器当前使用的飞行安全数据库版本号。', 'r', '1'],
  ['offline_map_enable', '离线地图开关', 'bool', '{"false":"关闭","true":"开启"}', '是否允许飞行器自动同步和使用离线地图。', 'r', '1'],
  ['current_rth_mode', '当前返航高度模式', 'enum_int', '{"0":"智能高度","1":"设定高度"}', '飞行器当前实际采用的返航高度模式。', 'r', '1'],
  ['rth_mode', '返航高度模式设置', 'enum_int', '{"0":"智能高度","1":"设定高度"}', '返航高度模式的配置值；设定高度模式使用返航高度参数。', 'r', '1'],
  ['rth_altitude', '返航高度', 'int', '{"max":500,"min":20,"unit_name":"米 / m"}', '飞行器执行返航时使用的目标高度。', 'rw', '0'],
  ['rc_lost_action', '失控动作', 'enum_int', '{"0":"悬停","1":"降落","2":"返航"}', '遥控或控制链路丢失后飞行器执行的安全动作。', 'rw', '0'],
  ['distance_limit_status', '限远状态', 'struct', '', '飞行器限远功能的设置值和接近限制状态。', 'rw', '0'],
  ['»state', '是否开启限远', 'enum_int', '{"0":"未设置","1":"已设置"}', '飞行器是否启用了最大飞行距离限制。', '', '0'],
  ['»distance_limit', '限远距离', 'int', '{"max":"8000","min":"15","step":"1","unit_name":"米 / m"}', '飞行器允许远离起飞点的最大距离。', '', '0'],
  ['»is_near_distance_limit', '是否接近限远', 'enum_int', '{"0":"未接近","1":"接近限制"}', '飞行器是否已经接近设定的最大飞行距离。', '', '0'],
  ['obstacle_avoidance', '飞行器避障状态', 'struct', '', '飞行器各方向视觉避障功能的开关状态。', 'rw', '0'],
  ['»horizon', '水平避障', 'enum_int', '{"0":"关闭","1":"开启"}', '水平方向避障功能是否开启。', '', '0'],
  ['»upside', '上视避障', 'enum_int', '{"0":"关闭","1":"开启"}', '上方避障功能是否开启。', '', '0'],
  ['»downside', '下视避障', 'enum_int', '{"0":"关闭","1":"开启"}', '下方避障功能是否开启。', '', '0'],
  ['is_near_area_limit', '是否接近限飞区', 'enum_int', '{"0":"未接近","1":"接近限飞区"}', '飞行器是否接近飞行安全数据库中的限飞区域。', 'r', '0'],
  ['is_near_height_limit', '是否接近限高', 'enum_int', '{"0":"未接近","1":"接近限制"}', '飞行器是否接近当前设置的最大飞行高度。', 'r', '0'],
  ['height_limit', '飞行器限高', 'int', '{"max":"1500","min":"20","step":"1","unit_name":"米 / m"}', '飞行器允许达到的最大相对飞行高度。', 'rw', '0'],
  ['night_lights_state', '夜航灯状态', 'enum_int', '{"0":"关闭","1":"打开"}', '飞行器夜航灯当前的开关状态。', 'rw', '0'],
  ['activation_time', '飞行器激活时间', 'int', '{"unit_name":"秒 / s"}', '飞行器首次激活的 Unix 时间戳。', 'r', '0'],
  ['maintain_status', '保养信息', 'struct', '', '飞行器的保养状态和最近一次保养记录。', 'r', '0'],
  ['»maintain_status_array', '保养记录', 'array', '{"size":-,"item_type":"struct"}', '飞行器各类保养项目的状态记录。', '', '0'],
  ['»»state', '保养状态', 'enum_int', '{"0":"无保养","1":"有保养"}', '当前是否存在已记录的保养信息。', '', '0'],
  ['»»last_maintain_type', '上一次保养类型', 'enum_int', '{"1":"基础保养","2":"常规保养","3":"深度保养"}', '飞行器最近一次完成的保养级别。', '', '0'],
  ['»»last_maintain_time', '上一次保养时间', 'date', '{"unit_name":"秒 / s"}', '最近一次保养的 Unix 时间戳。', '', '0'],
  ['»»last_maintain_flight_time', '保养时累计航时', 'int', '{"unit_name":"小时 / h"}', '最近一次保养时记录的累计飞行时长。', '', '0'],
  ['»»last_maintain_flight_sorties', '保养时累计架次', 'int', '{"min":"0","step":"1"}', '最近一次保养时记录的累计飞行架次。', '', '0'],
  ['total_flight_sorties', '累计飞行架次', 'int', '{"min":"0","step":"1"}', '飞行器从投入使用以来累计完成的飞行架次。', 'r', '0'],
  ['type_subtype_gimbalindex', '云台与负载状态', 'struct', '', '指定负载编号对应的云台姿态和变焦状态。', 'r', '0'],
  ['»gimbal_pitch', '云台俯仰角', 'double', '{"max":"180","min":"-180","step":0.1,"unit_name":"度 / °"}', '云台俯仰轴当前角度。', '', '0'],
  ['»gimbal_roll', '云台横滚角', 'double', '{"max":"180","min":"-180","step":0.1,"unit_name":"度 / °"}', '云台横滚轴当前角度。', '', '0'],
  ['»gimbal_yaw', '云台偏航角', 'double', '{"max":"180","min":"-180","step":0.1,"unit_name":"度 / °"}', '云台偏航轴当前角度。', '', '0'],
  ['»payload_index', '负载索引', 'text', '', '云台对应的负载索引，格式为 {type-subtype-gimbalindex}。', '', '0'],
  ['»zoom_factor', '变焦倍数', 'double', '', '该负载相机当前的变焦倍数。', '', '0'],
  ['track_id', '航迹 ID', 'text', '{"length":"64"}', '用于关联飞行器当前航迹数据的标识符。', 'r', '0'],
  ['position_state', '定位搜星状态', 'struct', '', '飞行器 GNSS 与 RTK 的搜星和收敛状态。', 'r', '0'],
  ['»is_fixed', 'RTK 收敛状态', 'enum_int', '{"0":"未开始","1":"收敛中","2":"收敛成功","3":"收敛失败"}', 'RTK 定位解算当前是否完成收敛。', '', '0'],
  ['»quality', '定位质量档位', 'enum_int', '{"1":"1档","2":"2档","3":"3档","4":"4档","5":"5档","10":"RTK fixed"}', '当前卫星定位或 RTK 定位质量等级。', '', '0'],
  ['»gps_number', 'GPS 搜星数量', 'int', '', '当前可用于定位的 GPS 卫星数量。', '', '0'],
  ['»rtk_number', 'RTK 搜星数量', 'int', '', '当前可用于 RTK 解算的卫星数量。', '', '0'],
  ['storage', '机载存储容量', 'struct', '', '飞行器机载存储空间的总量和已使用量。', 'r', '0'],
  ['»total', '总容量', 'int', '{"unit_name":"千字节 / KB"}', '机载存储空间的总容量。', '', '0'],
  ['»used', '已使用容量', 'int', '{"unit_name":"千字节 / KB"}', '机载存储空间已经占用的容量。', '', '0'],
  ['battery', '飞行器电池信息', 'struct', '', '飞行器整机电量、续航估算和每块电池的详细状态。', 'r', '0'],
  ['»capacity_percent', '总剩余电量', 'int', '{"max":100,"min":0,"unit_name":"百分比 / %"}', '飞行器电池组当前的总剩余电量百分比。', '', '0'],
  ['»remain_flight_time', '剩余飞行时间', 'int', '{"unit_name":"秒 / s"}', '根据当前状态估算的剩余可飞行时间。', '', '0'],
  ['»return_home_power', '返航所需电量', 'int', '{"max":100,"min":0,"unit_name":"百分比 / %"}', '从当前位置安全返航预计需要的电量百分比。', '', '0'],
  ['»landing_power', '强制降落电量', 'int', '{"max":100,"min":0,"unit_name":"百分比 / %"}', '触发强制降落保护的电量百分比。', '', '0'],
  ['»batteries', '电池详细信息', 'array', '{"size":-,"item_type":"struct"}', '飞行器每块电池的独立状态数据。', '', '0'],
  ['»»capacity_percent', '电池剩余电量', 'int', '{"max":100,"min":0,"unit_name":"百分比 / %"}', '当前这块电池的剩余电量百分比。', '', '0'],
  ['»»index', '电池序号', 'int', '{"min":"0"}', '电池在飞行器电池组中的位置序号。', '', '0'],
  ['»»sn', '电池 SN', 'text', '', '电池的设备序列号。', '', '0'],
  ['»»type', '电池类型', 'enum_int', '{}', '电池的主类型枚举值。', '', '0'],
  ['»»sub_type', '电池子类型', 'enum_int', '{}', '电池的子类型枚举值。', '', '0'],
  ['»»firmware_version', '电池固件版本', 'text', '', '电池管理系统当前的固件版本。', '', '0'],
  ['»»loop_times', '电池循环次数', 'int', '', '电池已经完成的充放电循环次数。', '', '0'],
  ['»»voltage', '电池电压', 'int', '{"unit_name":"毫伏 / mV"}', '当前这块电池的端电压。', '', '0'],
  ['»»temperature', '电池温度', 'float', '{"unit_name":"摄氏度 / °C"}', '当前这块电池的内部温度，通常保留一位小数。', '', '0'],
  ['»»high_voltage_storage_days', '高电压存储天数', 'int', '{"unit_name":"日 / day"}', '电池处于高电量存储状态的累计天数。', '', '0'],
  ['total_flight_distance', '累计飞行里程', 'float', '{"unit_name":"米 / m"}', '飞行器从投入使用以来累计飞行的距离。', 'r', '0'],
  ['total_flight_time', '累计飞行航时', 'int', '{"unit_name":"秒 / s"}', '飞行器从投入使用以来累计飞行的时间。', 'r', '0'],
  ['serious_low_battery_warning_threshold', '严重低电量阈值', 'int', '{"max":100,"min":0,"unit_name":"百分比 / %"}', '用户设置的严重低电量告警百分比。', 'r', '1'],
  ['low_battery_warning_threshold', '低电量阈值', 'int', '{"max":100,"min":0,"unit_name":"百分比 / %"}', '用户设置的低电量告警百分比。', 'r', '1'],
  ['control_source', '当前控制源', 'text', '', '当前拥有飞行器控制权的设备或浏览器标识。', 'r', '1'],
  ['wind_direction', '估算风向', 'enum_int', '{"1":"正北","2":"东北","3":"东","4":"东南","5":"南","6":"西南","7":"西","8":"西北"}', '根据飞行器姿态估算的当前风向，仅供飞行参考。', 'r', '0'],
  ['wind_speed', '估算风速', 'float', '{"unit_name":"米每秒 / m/s"}', '根据飞行器姿态推测的风速，存在误差，不能作为气象数据使用。', 'r', '0'],
  ['home_distance', '距 Home 点距离', 'float', '{"unit_name":"米 / m"}', '飞行器当前位置与 Home 点之间的直线距离。', 'r', '0'],
  ['home_latitude', 'Home 点纬度', 'float', '{"unit_name":"度 / °"}', '当前 Home 点的纬度坐标。', 'r', '1'],
  ['home_longitude', 'Home 点经度', 'float', '{"unit_name":"度 / °"}', '当前 Home 点的经度坐标。', 'r', '1'],
  ['attitude_head', '飞行器偏航角', 'int', '{"unit_name":"度 / °"}', '机头方向相对真北方向的偏航轴角度。', 'r', '0'],
  ['attitude_roll', '飞行器横滚角', 'float', '{"unit_name":"度 / °"}', '飞行器机体绕前后轴的横滚角度。', 'r', '0'],
  ['attitude_pitch', '飞行器俯仰角', 'float', '{"unit_name":"度 / °"}', '飞行器机体绕左右轴的俯仰角度。', 'r', '0'],
  ['elevation', '相对起飞点高度', 'float', '{"unit_name":"米 / m"}', '飞行器当前位置相对于起飞点的高度。', 'r', '0'],
  ['height', '绝对高度', 'float', '{"unit_name":"米 / m"}', '相对地球椭球面的高度，等于相对起飞点高度加起飞点椭球高。', 'r', '0'],
  ['latitude', '当前位置纬度', 'float', '{"unit_name":"度 / °"}', '飞行器当前位置的纬度坐标。', 'r', '0'],
  ['longitude', '当前位置经度', 'float', '{"unit_name":"度 / °"}', '飞行器当前位置的经度坐标。', 'r', '0'],
  ['vertical_speed', '垂直速度', 'float', '{"unit_name":"米每秒 / m/s"}', '飞行器在垂直方向上的实时速度。', 'r', '0'],
  ['horizontal_speed', '水平速度', 'float', '{"unit_name":"米每秒 / m/s"}', '飞行器在水平方向上的合成实时速度。', 'r', '0'],
  ['firmware_upgrade_status', '固件升级状态', 'enum_int', '{"0":"未升级","1":"升级中"}', '飞行器当前是否正在执行固件升级。', 'r', '1'],
  ['compatible_status', '固件一致性', 'enum_int', '{"0":"无需一致性升级","1":"需要一致性升级"}', '飞行器各模块固件版本是否与系统要求的版本一致。', 'r', '1'],
  ['firmware_version', '飞行器固件版本', 'text', '{"length":"64"}', '飞行器当前安装的整机固件版本。', 'r', '1'],
  ['gear', '飞行档位', 'enum_int', '{"0":"A","1":"P","2":"NAV","3":"FPV","4":"FARM","5":"S","6":"F","7":"M","8":"G","9":"T"}', '飞行器当前使用的飞行控制档位。', 'r', '0'],
  ['mode_code_reason', '当前状态原因', 'int', '', '飞行器进入当前飞行状态的触发原因枚举值。', 'r', '1'],
  ['mode_code', '飞行器状态', 'enum_int', '{"0":"待机","1":"起飞准备","2":"起飞准备完毕","3":"手动飞行","4":"自动起飞","5":"航线飞行","6":"全景拍照","7":"智能跟随","8":"ADS-B 躲避","9":"自动返航","10":"自动降落","11":"强制降落","12":"三桨叶降落","13":"升级中","14":"未连接","15":"APAS","16":"虚拟摇杆状态","17":"指令飞行","18":"空中 RTK 收敛模式","19":"机场选址中"}', '飞行器当前所处的飞行或作业状态。', 'r', '0'],
] satisfies readonly DjiFieldRow[]

export const DJI_AIRCRAFT_FIELDS = Object.freeze(buildDjiFieldMetadata(DJI_AIRCRAFT_FIELD_ROWS))

const AIRCRAFT_FIELD_BY_PATH = new Map(DJI_AIRCRAFT_FIELDS.map((metadata) => [metadata.path, metadata]))

export const getDjiAircraftFieldMetadata = (path: string): DjiFieldMetadata | undefined => {
  const normalizedPath = path
    .split('.')
    .filter((part) => !/^\d+$/.test(part))
    .join('.')
  return AIRCRAFT_FIELD_BY_PATH.get(normalizedPath)
}
